import type { Word, Category } from "@/types/index"

export const initialWords: Word[] = [
  {
    id: "1",
    text: "مرحبا -- Hello",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "2",
    text: "شكرا -- Thank you",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "3",
    text: "من فضلك -- Please",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "4",
    text: "عفوا -- Excuse me / You're welcome",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "5",
    text: "نعم -- Yes",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-6",
    text: "software crafters حرفيي البرمجيات",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-7",
    text: "some languages enforce indentation rules (enforce تفرض)",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-8",
    text: "(enforce تفرض)",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-9",
    text: "you will have easier time reading the text (سيكون من الأسهل)",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-10",
    text: "chunk of code.",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-11",
    text: "retain the precision الحفاظ",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-12",
    text: "accomodate the value استيعاب",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-13",
    text: "incorporate static variables.",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-14",
    text: "discrepancies التناقضات",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-15",
    text: "when the app starts up",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-16",
    text: "laws & regulations القوانين والأنظمة",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-17",
    text: "level of granularity - مستوى التفاصيل - مستوى الدقة",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-18",
    text: "we can not have any other access modifier in an interface declaration, that is the case with class too.",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-19",
    text: "strictly speaking",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-20",
    text: "in under a minute",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-21",
    text: "so to map a Map we use @MapKey in combination with @ElementCollection & @CollectionTable annotations",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-22",
    text: "in combination with بالاشتراك مع",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-23",
    text: "the moment you add this dependency...; في اللحظة التي",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-24",
    text: "right most click on it",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-25",
    text: "once in a while من حين لآخر",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-26",
    text: "relay the error",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-27",
    text: "the opposite sort of things happen",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-28",
    text: "please notice that",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-29",
    text: "by convention static final variables are all caps separated by underscores",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-30",
    text: "in which case (in this case)",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-31",
    text: "ideally with good development & testing effort we would want as minimal runtime exceptions as possible",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-32",
    text: "with the exception of باستثناء",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-33",
    text: "this is not mandatory هذا ليس إلزاميًا",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-34",
    text: "it might be worthwhile to قد يكون من المفيد",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-35",
    text: "provisioning",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-36",
    text: "turn it into",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-37",
    text: "comes down to",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-38",
    text: "utility",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-39",
    text: "integrity سلامة",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-40",
    text: "insights",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-41",
    text: "get insights about your cluster",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-42",
    text: "mimic that external usecase تقليد. محاكاة",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-43",
    text: "simulate محاكاة",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-44",
    text: "emulate",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-45",
    text: "pertain",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-46",
    text: "onwards",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-47",
    text: "peek نظرة خاطفة",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-48",
    text: "pull elements from db",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-49",
    text: "pull elements from the list",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-50",
    text: "jump to (go to)",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-51",
    text: "switch to",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-52",
    text: "accidental/accidentally عرضي/غير مقصود",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-53",
    text: "so we should write each test as if it's the only test in the world",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-54",
    text: "free up resources",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-55",
    text: "you should be good to go",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-56",
    text: "made available by vendors",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-57",
    text: "this helps move the technology forward in alignment with technology goals",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-58",
    text: "overarching شامل",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-59",
    text: "embraced احتضنت",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-60",
    text: "suitability for cloud environments",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-61",
    text: "and JMS which provide support for messaging",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-62",
    text: "With the prominence of JSON in web development مع بروز",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-63",
    text: "In an ever-connected digital world (an ever- دائمًا) في عالم رقمي متصل دائمًا",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-64",
    text: "failures are contained and don't propagate (contained تم احتواء)",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-65",
    text: "during service disruption (أثناء انقطاع الخدمة)",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-66",
    text: "disruption انقطاع",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-67",
    text: "notably على وجه الخصوص",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-68",
    text: "notable ملحوظا",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-69",
    text: "proactively بشكل استباقي",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-70",
    text: "It underscores the importance of ويؤكد على أهمية",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-71",
    text: "intricate معقد",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-72",
    text: "Inadequate غير مناسب",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-73",
    text: "once we have this in place",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-74",
    text: "with respect to the object in context",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
  {
    id: "word-75",
    text: "i.e none of the subclasses should ever be able to redefine it",
    statuses: [false, false, false, false],
    categoryIds: [],
    confusingWords: [],
    isImportant: false,
  },
]

export const initialCategories: Category[] = [
  {
    id: "cat1",
    name: "Greetings",
    color: "#3B82F6",
  },
  {
    id: "cat2",
    name: "Common Phrases",
    color: "#10B981",
  },
  {
    id: "cat3",
    name: "Numbers",
    color: "#F59E0B",
  },
]
